#도커파일같은거 load 및 세이브




### 남은 설치파일 참고

# GATEKEEPER 재설치, 위치는 ISTIO 2번파일(tracing.yaml)
# istio의jaeger, istio 설치
# kubeflow의 9번 설치, 아마 knative인듯? 그리고 knative들은 이미지 뒤에가 ~~:v1.1.1.1 임. 다른 이미지들은 ~~:1.1.1임


#변수
export GATEKEEPER_VERSION=10.0.0
export REGISTRY=

 

####
pull
####
docker pull docker.io/istio/proxyv2:1.3.1 

docker pull quay.io/keycloak/keycloak-gatekeeper:${GATEKEEPER_VERSION}

docker pull gcr.io/knative-releases/knative.dev/serving/cmd/activator:v0.14.3
docker pull gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler:v0.14.3
docker pull gcr.io/knative-releases/knative.dev/serving/cmd/controller:v0.14.3
docker pull gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook:v0.14.1
docker pull gcr.io/knative-releases/knative.dev/net-istio/cmd/controller:v0.14.1
docker pull gcr.io/knative-releases/knative.dev/serving/cmd/webhook:v0.14.3
docker pull gcr.io/knative-releases/knative.dev/serving/cmd/queue:v0.14.3


####
save
####
sudo docker save docker.io/istio/proxyv2:1.3.1  > proxyv2:1.3.1.tar

sudo docker save quay.io/keycloak/keycloak-gatekeeper:${GATEKEEPER_VERSION} > keycloak-gatekeeper:${GATEKEEPER_VERSION}.tar

sudo docker save gcr.io/knative-releases/knative.dev/serving/cmd/activator:v0.14.3 > activator:v0.14.3.tar
sudo docker save gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler:v0.14.3 > autoscaler:v0.14.3.tar
sudo docker save gcr.io/knative-releases/knative.dev/serving/cmd/controller:v0.14.3 > controller:v0.14.3.tar
sudo docker save gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook:v0.14.1 > webhook:v0.14.1.tar
sudo docker save gcr.io/knative-releases/knative.dev/net-istio/cmd/controller:v0.14.1 > controller:v0.14.1.tar
sudo docker save gcr.io/knative-releases/knative.dev/serving/cmd/webhook:v0.14.3 > webhook:v0.14.3.tar
sudo docker save gcr.io/knative-releases/knative.dev/serving/cmd/queue:v0.14.3 > queue:v0.14.3.tar


####
load
####
sudo docker load < proxyv2:1.3.1.tar

sudo docker load < keycloak-gatekeeper:${GATEKEEPER_VERSION}.tar


sudo docker load < activator:v0.14.3.tar
sudo docker load < autoscaler:v0.14.3.tar
sudo docker load < controller:v0.14.3.tar
sudo docker load < webhook:v0.14.1.tar
sudo docker load < controller:v0.14.1.tar
sudo docker load < webhook:v0.14.3.tar
sudo docker load < queue:v0.14.3.tar




####
tag
####
sudo docker tag docker.io/istio/proxyv2:1.3.1 ${REGISTRY}/istio/proxyv2:1.3.1 

sudo docker tag quay.io/keycloak/keycloak-gatekeeper:${GATEKEEPER_VERSION} ${REGISTRY}/keycloak/keycloak-gatekeeper:${GATEKEEPER_VERSION}

sudo docker tag gcr.io/knative-releases/knative.dev/serving/cmd/activator:v0.14.3 ${REGISTRY}/knative-releases/knative.dev/serving/cmd/activator:v0.14.3
sudo docker tag gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler:v0.14.3 ${REGISTRY}/knative-releases/knative.dev/serving/cmd/autoscaler:v0.14.3
sudo docker tag gcr.io/knative-releases/knative.dev/serving/cmd/controller:v0.14.3 ${REGISTRY}/knative-releases/knative.dev/serving/cmd/controller:v0.14.3
sudo docker tag gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook:v0.14.1 ${REGISTRY}/knative-releases/knative.dev/net-istio/cmd/webhook:v0.14.1
sudo docker tag gcr.io/knative-releases/knative.dev/net-istio/cmd/controller:v0.14.1 ${REGISTRY}/knative-releases/knative.dev/net-istio/cmd/controller:v0.14.1
sudo docker tag gcr.io/knative-releases/knative.dev/serving/cmd/webhook:v0.14.3 ${REGISTRY}/knative-releases/knative.dev/serving/cmd/webhook:v0.14.3
sudo docker tag gcr.io/knative-releases/knative.dev/serving/cmd/queue:v0.14.3 ${REGISTRY}/knative-releases/knative.dev/serving/cmd/queue:v0.14.3

####
push
####
sudo docker push ${REGISTRY}/istio/proxyv2:1.3.1

sudo docker push ${REGISTRY}/keycloak/keycloak-gatekeeper:${GATEKEEPER_VERSION}

sudo docker push ${REGISTRY}/knative-releases/knative.dev/serving/cmd/activator:v0.14.3
sudo docker push ${REGISTRY}/knative-releases/knative.dev/serving/cmd/autoscaler:v0.14.3
sudo docker push ${REGISTRY}/knative-releases/knative.dev/serving/cmd/controller:v0.14.3
sudo docker push ${REGISTRY}/knative-releases/knative.dev/net-istio/cmd/webhook:v0.14.1
sudo docker push ${REGISTRY}/knative-releases/knative.dev/net-istio/cmd/controller:v0.14.1
sudo docker push ${REGISTRY}/knative-releases/knative.dev/serving/cmd/webhook:v0.14.3
sudo docker push ${REGISTRY}/knative-releases/knative.dev/serving/cmd/queue:v0.14.3

